### ISSUE TITLE
Tests fail with current TypeScript 2.1.4

### ISSUE THREAD

**Issue by BrainCrumbz** [auth0/angular2-jwt#261] opened 2017-01-03 10:45 UTC
With package.json dependency stated as `"typescript": "^2.0.2"`, currently after `npm install` one gets typescript 2.1.4. When building and then running tests, one incurs into following error:

> TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (D:\WS\JS\angular2-jwt\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (D:\WS\JS\angular2-jwt\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (D:\WS\JS\angular2-jwt\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (D:\WS\JS\angular2-jwt\node_modules\awesome-typescript-loader\src\index.ts:18:18)
    at WEBPACK_CORE_LOADER_EXECUTION (D:\WS\JS\angular2-jwt\node_modules\webpack-core\lib\NormalModuleMixin.js:155:71)
    at runSyncOrAsync (D:\WS\JS\angular2-jwt\node_modules\webpack-core\lib\NormalModuleMixin.js:155:93)
    at nextLoader (D:\WS\JS\angular2-jwt\node_modules\webpack-core\lib\NormalModuleMixin.js:290:3)
    at D:\WS\JS\angular2-jwt\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (D:\WS\JS\angular2-jwt\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at D:\WS\JS\angular2-jwt\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3) 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (D:\\WS\\JS\\angular2-jwt\\node_modules\\awesome-typescript-loader\\src\\instance.ts:266:72)\n    at Object.ensureInstance (D:\\WS\\JS\\angular2-jwt\\node_modules\\awesome-typescript-loader\\src\\instance.ts:145:5)\n    at compiler (D:\\WS\\JS\\angular2-jwt\\node_modules\\awesome-typescript-loader\\src\\index.ts:37:20)\n    at Object.loader (D:\\WS\\JS\\angular2-jwt\\node_modules\\awesome-typescript-loader\\src\\index.ts:18:18)\n    at WEBPACK_CORE_LOADER_EXECUTION (D:\\WS\\JS\\angular2-jwt\\node_modules\\webpack-core\\lib\\NormalModuleMixin.js:155:71)\n    at runSyncOrAsync (D:\\WS\\JS\\angular2-jwt\\node_modules\\webpack-core\\lib\\NormalModuleMixin.js:155:93)\n    at nextLoader (D:\\WS\\JS\\angular2-jwt\\node_modules\\webpack-core\\lib\\NormalModuleMixin.js:290:3)\n    at D:\\WS\\JS\\angular2-jwt\\node_modules\\webpack-core\\lib\\NormalModuleMixin.js:259:5\n    at Storage.finished (D:\\WS\\JS\\angular2-jwt\\node_modules\\webpack\\node_modules\\enhanced-resolve\\lib\\CachedInputFileSystem.js:38:16)\n    at D:\\WS\\JS\\angular2-jwt\\node_modules\\graceful-fs\\graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)'
[... rest omitted...]

This seems to be somewhat a known issue, see https://github.com/s-panferov/awesome-typescript-loader/issues/190 and https://github.com/s-panferov/awesome-typescript-loader/issues/293. Current solution seems to be nailing TypeScript version to e.g. 2.0.10 or earlier, down to 2.0.3.

Would you consider a PR with such a solution? Thanks!

**Comment by escardin** [comment] 2017-01-03 14:52
I would prefer to fix the root cause, and stay compatible with the widest range of versions where possible. I will add an issue to add/switch to yarn for clamping versions though.

I think our config file has problems already anyway.

**Comment by BrainCrumbz** [comment] 2017-01-04 11:21
Not sure what does it mean in this case to fix the root cause. There seems to be an issue between TypeScript and awesome-typescript-loader, which is thus out of this library control. The only thing you can do is clamp version, and you can do that with npm already.

Re. config file, not sure if you mean package.json or other. If it's package.json, well, we all can proceed and fix one thing at a time, with focused PRs.

If you agree, we can go on and clamp TS version on current package.json. Otherwise, happy to speak about other ways. Cheers!

**Comment by escardin** [comment] 2017-01-04 14:14
I mean the tsconfig.json. No I don't agree with clamping the version at this time.

**Comment by BrainCrumbz** [comment] 2017-01-04 15:21
Ok. How do you think we can get back to running test successfully?

**Comment by brian428** [comment] 2017-01-09 15:24
Just FYI, Angular itself doesn't support TS 2.1 yet. So you probably shouldn't be using it yet. https://github.com/angular/angular/issues/13715

**Comment by BrainCrumbz** [comment] 2017-01-09 15:54
Yep, that's why staying on TS 2.0x seems reasonable as of now

**Comment by escardin** [comment] 2017-01-11 14:26
This should be resolved in 0.1.28. Please reopen if that is not the case.

**Closed** 2017-01-11 14:28 UTC
Labels: bug
