### ISSUE TITLE
Cannot file module on v4.1.0

### ISSUE THREAD

**Issue by JaxonWright** [auth0/angular2-jwt#655] opened 2020-05-15 16:40 UTC
### Description

When updating to version 4.1.0, I am no longer able to run my Angular project, as it cannot find the `@auth0/angular-jwt` library. Downgrading to 4.0.0 works fine.

### Reproduction
1) change your `package.json` in such a way where the latest version of `@auth0/angular-jwt` is set
2) run `npm install`
3) import something from the library somewhere in your Angular project, like the `app.module`
3) run `ng serve` and observe that it fails to compile due to it not being able to find the module

### Environment

- **Version of this library used:** 4.1.0
- **Version of the platform or framework used, if applicable:** Angular 9.1.7
- **Other relevant versions (language, server software, OS, browser):** N/A
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by Sambego** [comment] 2020-05-15 16:41
This is a duplicate of #654, please upgrade to `4.1.1`.

**Closed by Sambego** 2020-05-15 16:41 UTC

**Comment by JaxonWright** [comment] 2020-05-15 16:44
Ope. did not see that. Sorry about that.
