### ISSUE TITLE
Crash in Angular2 RC6

### ISSUE THREAD

**Issue by charsleysa** [auth0/angular2-jwt#143] opened 2016-09-01 02:08 UTC
Angular2 RC6 removes a lot of deprecated API.

Angular2-JWT uses the `provide()` method from @angular/core which has been removed.

Two approaches can be taken to fix this:
- Frist is to convert the code to export an NgModule
- Second is to convert the code to use the new Provider structure

/cc @chenkie

**Comment by ShadowManu** [comment] 2016-09-01 03:01
I've submitted a PR that tries to fast-fix that call. I've also test-published a `npm` package with name and version `@shadowmanu/angular2-jwt@0.1.20-rc6-fix`.

@charsleysa @/mantainers can you check either the PR or if using the `npm` package for testing the fix works completely? My own application has a lot of bugs that I need to solve to assure the fix is enough for it to work (at least the `provide` errors SystemJS was throwing at me dissapeared).

**Comment by ShadowManu** [comment] 2016-09-01 03:23
After fixing some other stuff, seems like its working, at least with a custom provider. If of any interest, in our case, we define our provider like this (don't ask all the details of it since it was done by a team member) :

```
'use strict';

import { AuthHttp, AuthConfig } from 'angular2-jwt';
import { Http } from '@angular/http';

export let customHttpProvider: any = {
  provide: AuthHttp,
  useFactory: (http: Http) => {
    let config: AuthConfig = new AuthConfig({
      noJwtError: true,
      tokenName: 'token',
      tokenGetter: () => localStorage.getItem('token')
    });
    return new AuthHttp(config, http);
  },
  deps: [Http]
};
```

Anyway, the `Authorization` header gets sent with requests, no issues at my usage.

**Comment by charsleysa** [comment] 2016-09-01 03:55
@ShadowManu @chenkie I've made changes using the second approach.
There were other changes required for RC6 such as upgrading to Typescript 2.0.2.
https://github.com/charsleysa/angular2-jwt

**Comment by ShadowManu** [comment] 2016-09-01 04:06
AFAIK, change to TS2 is not required. Why is it?

PS: I needed the `npm` approach since its easier to setup/replace with `jspm` in which our build is based for now.

**Comment by charsleysa** [comment] 2016-09-01 04:18
@ShadowManu from what I know Angular themselves have moved to Typescript 2 and it is now stable.
I don't think it's strictly required but recommended.

I would personally recommend it due to the upgrades in type checking and configuration.

**Comment by ShadowManu** [comment] 2016-09-01 04:20
Surely enough. Just that TS 2.0 was in beta (not crashing at all, I know), and its just recently moving to rc's and stable releases.

**Comment by charsleysa** [comment] 2016-09-01 04:42
@ShadowManu I've corrected my comment above. TS2 is RC currently and will soon be stable.

**Comment by escardin** [comment] 2016-09-01 14:04
TS2 is a compile time requirement. It won't affect consumers of the library (or it shouldn't).

**Comment by fxck** [comment] 2016-09-01 14:22
So there are already three PRs fixing rc.6. Are you guys trying to make @chenkie's phone vibrate enough so he wakes up or something? Should I send another PR as well? ;)

**Comment by ShadowManu** [comment] 2016-09-01 19:28
Meh, I needed to fix stuff, whoever does it first (and better) and gets merged + released, makes my life happier ;)

**Comment by charsleysa** [comment] 2016-09-01 20:40
@escardin the Angular2 Compiler CLI uses Typescript 2 for compiling consumer code from what I can see.

**Comment by binarious** [comment] 2016-09-04 13:23
@ShadowManu I can't install your npm package: 
```
'@shadowmanu/angular2-jwt' is not in the npm registry.
```

**Comment by ShadowManu** [comment] 2016-09-04 17:49
I unpublished the `npm` package since the crash was fixed in #145 and published in version `0.1.21`. Looks like you're getting my github branch, but that's also no longer needed. Update and you'll be good.

PS:  the main topic of this thread is fixed, issue should be closed.

**Comment by charsleysa** [comment] 2016-09-04 20:44
@ShadowManu #145 has some logic which can lead to false positives during the isTokenExpired check. In my opinion I think this issue should still be open until it's resolved as the fix that was merged is inadequate.

**Comment by ShadowManu** [comment] 2016-09-04 20:46
I didn't checked that out (That's on the author and the merger), but look at the title of the issue. Its not a crash, its a bug for a different topic. Still believe the main topic is fixed.

**Comment by lewiswebber** [comment] 2016-09-04 21:45
Maybe not a direct answer or related to the question but might be worth noting:
I imported AuthHttp from `angular2-jwt/angular2-jwt` in my main app module to register as a provider but imported AuthHttp from `angular2-jwt` in my `auth.service.ts`. This caused a "no provider for AuthHttp" error. After hours of debugging I fixed this by importing any AuthHttp classes from the same `angular2-jwt` file. This was caused by WebStorm as I took over this project from another developer.

**Comment by lewiswebber** [comment] 2016-09-04 21:46
If anyone's interested, this is my working configuration for setting up the provider:
```javascript
...
    {
        provide: AuthHttp,
        useFactory: (http) => {
            return new AuthHttp(new AuthConfig({
                headerName: 'Authorization',
                headerPrefix: 'Bearer',
                // tokenName: 'jwt_token',
                // tokenGetter: localStorage.getItem('jwt_token'),
                globalHeaders: [{'Content-Type': 'application/json'}],
                noJwtError: true,
                noTokenScheme: true
            }), http);
        },
        deps: [Http]
    },
...
```

**Comment by charsleysa** [comment] 2016-09-04 21:53
@lewiswebber you have to use provideAuth from angular2-jwt package.

e.g.
```ts
        provideAuth({
            headerName: 'X-Access-Token',
            noTokenScheme: true,
            globalHeaders: [
                { 'Content-Type': 'application/json' }
            ]
        }),
```

**Closed** 2016-09-18 20:46 UTC
