### ISSUE TITLE
'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

### ISSUE THREAD

**Issue by Prabukmca** [auth0/angular2-jwt#762] opened 2023-01-10 11:27 UTC
We are trying to upgrade our application from Angular 9 to 11, After upgrade, we unable to compile, we are facing the below issue,

Error: ./node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.js 426:17-39
"export 'ɵɵngDeclareNgModule' (imported as 'i0') was not found in '@angular/core'

![image](https://user-images.githubusercontent.com/20346782/211538421-9d6dbab7-b550-42ea-b836-72564dc9d09c.png)

![image](https://user-images.githubusercontent.com/20346782/211538629-0e618ab8-75cc-4001-8e69-d795e439be99.png)

![image](https://user-images.githubusercontent.com/20346782/211540454-525f2cb5-d5e3-4b6b-b2da-b97d253e3ab5.png)

We tried below steps to resolve this issue, but none worked.

1. Removed entire node modules and reinstalled.
2. Reinstalled tslib higher version and lower version both didn't worked.
3. Uninstalled the @angular/cli and @angular/core and reinstalled, none worked.
4. Downloaded this repository and analyzed the code "import as i0" found nowhere in this repo.

Please help us on this issue, Is there any specific steps we are missing?.

**Comment by frederikprijck** [comment] 2023-01-10 11:51
Duplicate of #750

**Closed by frederikprijck** 2023-01-10 11:51 UTC

**Comment by Prabukmca** [comment] 2023-01-10 13:24
Thanks for the response, We will stick with 5.0.2 for now.
