### ISSUE TITLE
Default tokenGetter not using tokenName in 0.1.25?

### ISSUE THREAD

**Issue by mwaltersva** [auth0/angular2-jwt#207] opened 2016-10-26 13:44 UTC
After updating to 0.1.25 from 0.1.24 my requests simply stopped sending. The observable error didn't have anything useful in it (message = "", name = "Error" 😭 ).

I had tokenName overriden to "token" in the provideAuth config. After setting the tokenGetter option to:

`() => localStorage.getItem('token')`

everything worked again. I don't believe tokenName is being used in 0.1.25.

**Comment by escardin** [comment] 2016-10-26 13:58
can you repro in a plunk?

**Comment by mwaltersva** [comment] 2016-10-26 14:45
[https://plnkr.co/edit/2JMlYLQ2X9DqqGl6kHf1?p=preview](url)

As is, the get request will not occur. Uncomment line 41 in src/app.ts and request will happen. This is speculation, but it seems like it's not finding the token and then not sending the request because the "token" is invalid.

**Comment by escardin** [comment] 2016-10-26 14:55
Thanks for the repro. For now you'll be stuck with the workaround you've come up with. The problem is with how we construct the authconfig object. I'll have to re-evaluate that and fix it up.

**Comment by thorsten** [comment] 2016-11-10 08:58
Any news on this issue?

**Comment by escardin** [comment] 2016-11-10 13:28
I haven't had time to work on it myself. It's due to how the constructor for authConfig was refactored between 1.24 and 1.25. I don't really want to revert what's there, but it should be something we can resolve without doing so. Contributions are welcome.

**Comment by rbaumi** [comment] 2017-01-09 12:59
@escardin - any progress on this?

**Comment by escardin** [comment] 2017-01-11 14:16
This should be resolved in 0.1.28. Please reopen if that is not the case.

**Comment by parliament718** [comment] 2017-01-17 19:34
It does not see to be resolved in 0.1.28. If I revert to not using a custom token name, there's no AuthHttpError

**Comment by mwaltersva** [comment] 2017-01-18 20:07
@parliament718 

I forked my original repo, but pointed it at 0.1.28... it seems to work as expected now. Your issue may be elsewhere:

[https://plnkr.co/edit/yiJ0B5wttQW5ZoRVDhhV?p=preview](Plunkr)

**Comment by escardin** [comment] 2017-01-19 13:50
Perhaps an old version in node modules?

**Comment by escardin** [comment] 2017-01-30 13:42
@parliament718 Did you get this fixed? I would like to close it.

**Comment by laterbreh** [comment] 2017-02-10 05:52
Hello, I was led here after some googling and reading just about every issue open in the repo. I was getting the "No JWT present or has expired", with the following:


```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
    tokenGetter: (() => sessionStorage.getItem('token')),
    globalHeaders: [{'Content-Type':'application/json'}],
    noTokenScheme: true
  }), http, options);
}
```

After seeing @mwaltersva's plnkr, I noticed that the tokenGetter line was commented out. Sure enough after I commented out that line, everything was working as it should. 

I am not sure if this was "fixed", but I nearly pulled my hair out following the documentation and using the tokenGetter line in my NG2 app. I am on version: `"angular2-jwt": "^0.1.28"`

**Comment by escardin** [comment] 2017-02-10 13:13
the token getter you've defined is using session storage. by default, if you don't provide a getter, we'll use the token name you passed to make one that fetches from local storage (not session storage). If you don't provide a token name either, we'll use the default there as well.

**Comment by laterbreh** [comment] 2017-02-10 17:10
Oh my god, I overlooked such a simple thing. What you just explained makes complete sense. I must have overlooked it last night while I was tired. Thank you for the explanation.

**Closed** 2017-02-10 17:10 UTC
Labels: bug
