### ISSUE TITLE
Uncaught Invalid provider - only instances of Provider and Type are allowed

### ISSUE THREAD

**Issue by keerthivasan-r** [auth0/angular2-jwt#90] opened 2016-05-24 09:54 UTC
When i add `AUTH_PROVIDERS` to 

```
// App
export * from './app.component';
export * from './app.service';
export * from './app.settings';
import {AppState} from './app.service';
import {AUTH_PROVIDERS} from 'angular2-jwt';

// Application wide providers
export const APP_PROVIDERS = [
  AppState,
  AUTH_PROVIDERS
];
```

it throws error saying

`zone.js:260 Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object]
`

**Comment by escardin** [comment] 2016-05-24 14:31
Try 
```
export const APP_PROVIDERS = [
  AppState,
  ...AUTH_PROVIDERS
];
```

The spread operator (`...` ) will expand the auth providers array and plausibly fix the error.

**Comment by keerthivasan-r** [comment] 2016-05-27 04:33
@escardin  it didn't fix the issue. Again, the same error is thrown

**Comment by keerthivasan-r** [comment] 2016-05-27 06:56
Does it work with Angular 2 rc1?

**Comment by escardin** [comment] 2016-05-27 12:40
I and others have been using angular2-jwt with rc1 since this lib was updated with support for it weeks ago. Can you make a plunk recreating your issue? You can fork this one: http://plnkr.co/edit/ceYAhQeVHQQhC3QAwIFY?p=preview

**Comment by andi1984** [comment] 2016-06-30 22:19
Same problem for me. Any idea?

**Comment by andi1984** [comment] 2016-06-30 22:59
I debugged it a bit. it seems that in ``_normalizeProviders`` it is failing for an instance check of type "Provider" which actually is the case.

Any ideas what is failing there? So are there multiple constructor functions for Providers? Don't get it...

**Comment by steelheaddigital** [comment] 2016-07-12 18:14
I'm having this problem with rc4. Everything worked great with rc1.

**Comment by escardin** [comment] 2016-07-15 15:38
Angular2-jwt works just fine with rc4 http://plnkr.co/edit/vWJA9DhVGCV1U7k086Rx?p=preview Please reproduce the issue you're having in a plunk so we can fix it, or close the issue.

**Closed** 2016-09-18 20:43 UTC
