### ISSUE TITLE
Build againt angular 10

### ISSUE THREAD

**Issue by Betalos** [auth0/angular2-jwt#665] opened 2020-06-25 12:58 UTC

**Comment by nanixne** [comment] 2020-06-25 15:38
I got warning when I built my Angular Project after update to 10, it seems the issue is url.js use CommonJS style to import modules.

**Comment by Sambego** [comment] 2020-06-29 14:33
Thanks for reporting! 

I've created a [pull request](#666) that will resolve those warnings complaining about url.js being a CommonJS lib. This will be included in the next version.

**Comment by piotter121** [comment] 2020-06-30 14:29
@Sambego When we could expect next version? It will be compatible with Angular 10?

**Comment by Sambego** [comment] 2020-06-30 14:32
A new version will be published in the next few days.

The current version `v4.2.0` works fine with Angular 10, but throws some warnings. These warnings will be gone in the next version of this library.

**Closed** 2020-07-07 08:07 UTC
Labels: has pull request

**Comment by Sambego** [comment] 2020-07-07 09:08
These warnings are gone in the latest version v5.0.0. When updating, be aware that version 5 also has some breaking changes concerning the allowed domains and dissallowed routes. https://github.com/auth0/angular2-jwt/blob/main/CHANGELOG.md
